<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RollForward>LatestMajor</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SkeletonKey</AssemblyName>
    <Product>SkeletonKey</Product>
    <AssemblyTitle>SkeletonKey</AssemblyTitle>
    <RootNamespace>WindowsInjector</RootNamespace>
    <ApplicationIcon>..\assets\SkeletonKey.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
